import type { EditorTheme } from '../types';

export const defaultTheme: EditorTheme = {
  root: 'blog-editor-root',
  paragraph: 'blog-editor-paragraph',
  heading: {
    h1: 'blog-editor-h1',
    h2: 'blog-editor-h2',
    h3: 'blog-editor-h3',
    h4: 'blog-editor-h4',
    h5: 'blog-editor-h5',
    h6: 'blog-editor-h6',
  },
  list: {
    nested: {
      listitem: 'blog-editor-nested-listitem',
    },
    ol: 'blog-editor-ol',
    ul: 'blog-editor-ul',
    listitem: 'blog-editor-listitem',
  },
  quote: 'blog-editor-quote',
  code: 'blog-editor-code',
  codeHighlight: {
    atrule: 'blog-editor-tokenAttr',
    attr: 'blog-editor-tokenAttr',
    boolean: 'blog-editor-tokenProperty',
    builtin: 'blog-editor-tokenSelector',
    cdata: 'blog-editor-tokenComment',
    char: 'blog-editor-tokenSelector',
    class: 'blog-editor-tokenFunction',
    'class-name': 'blog-editor-tokenFunction',
    comment: 'blog-editor-tokenComment',
    constant: 'blog-editor-tokenProperty',
    deleted: 'blog-editor-tokenProperty',
    doctype: 'blog-editor-tokenComment',
    entity: 'blog-editor-tokenOperator',
    function: 'blog-editor-tokenFunction',
    important: 'blog-editor-tokenVariable',
    inserted: 'blog-editor-tokenSelector',
    keyword: 'blog-editor-tokenAttr',
    namespace: 'blog-editor-tokenVariable',
    number: 'blog-editor-tokenProperty',
    operator: 'blog-editor-tokenOperator',
    prolog: 'blog-editor-tokenComment',
    property: 'blog-editor-tokenProperty',
    punctuation: 'blog-editor-tokenPunctuation',
    regex: 'blog-editor-tokenVariable',
    selector: 'blog-editor-tokenSelector',
    string: 'blog-editor-tokenSelector',
    symbol: 'blog-editor-tokenProperty',
    tag: 'blog-editor-tokenProperty',
    url: 'blog-editor-tokenOperator',
    variable: 'blog-editor-tokenVariable',
  },
  text: {
    bold: 'blog-editor-text-bold',
    italic: 'blog-editor-text-italic',
    underline: 'blog-editor-text-underline',
    strikethrough: 'blog-editor-text-strikethrough',
    code: 'blog-editor-text-code',
    highlight: 'blog-editor-text-highlight',
    subscript: 'blog-editor-text-subscript',
    superscript: 'blog-editor-text-superscript',
  },
  link: 'blog-editor-link',
  image: 'blog-editor-image',
  table: 'blog-editor-table',
  tableCell: 'blog-editor-tableCell',
  tableCellHeader: 'blog-editor-tableCellHeader',
  hr: 'blog-editor-hr',
};
